-- Add ACCUMULATOR support per FEI Article 229
DO $$ BEGIN
  CREATE TYPE "ClassCompetitionType" AS ENUM ('STANDARD', 'ACCUMULATOR');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE "AccumulatorMode" AS ENUM (
    'AGAINST_CLOCK_NO_JUMP_OFF',
    'AGAINST_CLOCK_WITH_JUMP_OFF',
    'NOT_AGAINST_CLOCK_WITH_JUMP_OFF'
  );
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE "JokerType" AS ENUM ('NONE', 'SINGLE_JOKER', 'DOUBLE_JOKER');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

ALTER TABLE "ShowClass"
  ADD COLUMN IF NOT EXISTS "competitionType" "ClassCompetitionType" NOT NULL DEFAULT 'STANDARD',
  ADD COLUMN IF NOT EXISTS "numberOfObstacles" INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS "accumulatorMode" "AccumulatorMode" NOT NULL DEFAULT 'AGAINST_CLOCK_NO_JUMP_OFF',
  ADD COLUMN IF NOT EXISTS "hasJoker" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "jokerType" "JokerType" NOT NULL DEFAULT 'NONE',
  ADD COLUMN IF NOT EXISTS "maxPoints" INTEGER NOT NULL DEFAULT 55;
