ALTER TABLE "ShowClass"
ADD COLUMN IF NOT EXISTS "courseLengthMeters" INTEGER,
ADD COLUMN IF NOT EXISTS "horseSpeedMetersPerMinute" INTEGER NOT NULL DEFAULT 350,
ADD COLUMN IF NOT EXISTS "maxObstacles" INTEGER NOT NULL DEFAULT 12,
ADD COLUMN IF NOT EXISTS "tableCDisobedienceWithKnockdownSeconds" INTEGER NOT NULL DEFAULT 6,
ADD COLUMN IF NOT EXISTS "applyTimeAdditionToClock" BOOLEAN NOT NULL DEFAULT false;
